services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      - QDRANT_STORAGE_PATH=/qdrant/storage
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
