services:
  pgvector:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: pgvector
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    pull_policy: always
    tty: true
    volumes:
      - ollama:/root/.ollama
      - ./pull_model.sh:/usr/local/bin/pull_model.sh
    ports:
      - "11434:11434"
    networks:
      - app-network
    entrypoint: ["/bin/sh", "/usr/local/bin/pull_model.sh"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  ollama:

networks:
  app-network:
    driver: bridge